// Generated by CoffeeScript 1.9.3
var addDayLabel, addReinou, addSitai, addSyokei, addUranai, calc, days, getMemberSelect, getSirokuroSelect, init, setMember;

days = 10;

$().ready(function() {
  setMember();
  init();
  $('#members').on('change', setMember);
  return $('#calc').on('click', calc);
});

calc = function() {
  var jr;
  return jr = new Jinro();
};

init = function() {
  var i, j, k;
  this.addDayLabel();
  this.addUranai(0, true);
  for (i = j = 1; j <= 3; i = ++j) {
    this.addUranai(i, false);
  }
  this.addReinou(0, true);
  for (i = k = 1; k <= 3; i = ++k) {
    this.addReinou(i, false);
  }
  this.addSyokei(true);
  return this.addSitai(true);
};

addDayLabel = function() {
  var d, j, ref, tr;
  tr = $('<tr>').append($('<th>'));
  tr.append($('<th>').html('名前'));
  for (d = j = 1, ref = days; 1 <= ref ? j <= ref : j >= ref; d = 1 <= ref ? ++j : --j) {
    tr.append($('<th>').html('' + d + '日目'));
  }
  return $('#dayLabel').append(tr);
};

addUranai = function(num, isFirst) {
  var d, j, ref, tr;
  if (isFirst == null) {
    isFirst = false;
  }
  tr = $('<tr>');
  if (isFirst) {
    tr.append($('<th>').html('占いCO').attr('rowspan', 9999));
  }
  tr.append($('<td>').append(getMemberSelect('memberSelect uranaiCO uranaiCOname' + num)));
  for (d = j = 1, ref = days; 1 <= ref ? j <= ref : j >= ref; d = 1 <= ref ? ++j : --j) {
    tr.append($('<td>').append(getMemberSelect('memberSelect uranaiCO uranaiCO' + num + '_' + d)).append(getSirokuroSelect('sirokuroSelect uranaiCO uranaiCOhantei' + num + '_' + d)));
  }
  return $('#uranaiForm').append(tr);
};

addReinou = function(num, isFirst) {
  var d, j, ref, tr;
  if (isFirst == null) {
    isFirst = false;
  }
  tr = $('<tr>');
  if (isFirst) {
    tr.append($('<th>').html('霊能CO').attr('rowspan', 9999));
  }
  tr.append($('<td>').append(getMemberSelect('memberSelect reinouCO reinouCOname' + num)));
  for (d = j = 1, ref = days; 1 <= ref ? j <= ref : j >= ref; d = 1 <= ref ? ++j : --j) {
    tr.append($('<td>').append(getMemberSelect('memberSelect reinouCO reinouCO' + num + '_' + d)).append(getSirokuroSelect('sirokuroSelect reinouCO reinouCOhantei' + num + '_' + d)));
  }
  return $('#reinouForm').append(tr);
};

addSyokei = function(isFirst) {
  var d, j, ref, tr;
  if (isFirst == null) {
    isFirst = false;
  }
  tr = $('<tr>');
  if (isFirst) {
    tr.append($('<th>').html('処刑').attr('rowspan', 9999));
  }
  tr.append($('<th>'));
  for (d = j = 1, ref = days; 1 <= ref ? j <= ref : j >= ref; d = 1 <= ref ? ++j : --j) {
    tr.append($('<td>').append(getMemberSelect('memberSelect syokei syokei' + d)));
  }
  return $('#syokeiForm').append(tr);
};

addSitai = function(isFirst) {
  var d, j, ref, tr;
  if (isFirst == null) {
    isFirst = false;
  }
  tr = $('<tr>');
  if (isFirst) {
    tr.append($('<th>').html('死体').attr('rowspan', 9999));
  }
  tr.append($('<th>'));
  for (d = j = 1, ref = days; 1 <= ref ? j <= ref : j >= ref; d = 1 <= ref ? ++j : --j) {
    tr.append($('<td>').append(getMemberSelect('memberSelect sitai sitai' + d)).append(getMemberSelect('memberSelect sitai sitai' + d)).append(getMemberSelect('memberSelect sitai sitai' + d)).append(getMemberSelect('memberSelect sitai sitai' + d)));
  }
  return $('#sitaiForm').append(tr);
};

setMember = function() {
  var i, j, members, ref;
  $('#tempOption').html('');
  members = $('#members').val().split("\n");
  $('#tempOption').append($('<option>').attr('value', -1).html('-'));
  for (i = j = 0, ref = members.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
    $('#tempOption').append($('<option>').attr('value', i).html(members[i]));
  }
  return $('.memberSelect').each(function() {
    var v;
    v = $(this).val();
    $(this).html($('#tempOption').html());
    return $(this).val(v);
  });
};

getMemberSelect = function(className) {
  return $('#tempOption').clone().removeAttr('id').removeClass('nodisplay').addClass(className).on('change', function() {
    if (Number($(this).val()) !== -1) {
      return $(this).addClass('active');
    } else {
      return $(this).removeClass('active');
    }
  });
};

getSirokuroSelect = function(className) {
  return $('#tempSirokuro').clone().removeAttr('id').removeClass('nodisplay').addClass(className).on('change', function() {
    if (Number($(this).val()) !== -1) {
      return $(this).addClass('active');
    } else {
      return $(this).removeClass('active');
    }
  });
};
